export const sections = [
  { label: '🎨 Arts', section: 'arts' },
  { label: '🚗 Automobiles', section: 'automobiles' },
  { label: '📚 Books', section: 'books' },
  { label: '💰 Business', section: 'business' },
  { label: '👗 Fashion', section: 'fashion' },
  { label: '🍳 Food', section: 'food' },
  { label: '🏥 Health', section: 'health' },
  { label: '🏡 Home', section: 'home' },
  { label: '📖 Magazine', section: 'magazine' },
  { label: '🎥 Movies', section: 'movies' },
  { label: '🇺🇸 National', section: 'national' },
  { label: '🗽 NY Region', section: 'nyregion' },
  { label: '⚰️ Obituaries', section: 'obituaries' },
  { label: '🔊 Opinion', section: 'opinion' },
  { label: '🤓 Politics', section: 'politics' },
  { label: '🏘️ Real Estate', section: 'realestate' },
  { label: '🔬 Science', section: 'science' },
  { label: '🏅 Sports', section: 'sports' },
  { label: '🏅 Sunday Review', section: 'sundayreview' },
  { label: '📱 Technology', section: 'technology' },
  { label: '🎭 Theater', section: 'theater' },
  { label: '✈️ Travel', section: 'travel' },
  { label: '⏫ Upshot', section: 'upshot' },
  { label: '🌎 World', section: 'world' }
];
