export const sections = [
  { searchTerm: 'national', label: 'Nation', icon: 'flag' },
  { searchTerm: 'arts', label: 'Arts', icon: 'palette' },
  { searchTerm: 'food', label: 'Food', icon: 'utensils' },
  { searchTerm: 'politics', label: 'Politics', icon: 'landmark' },
  { searchTerm: 'sports', label: 'Sports', icon: 'football-ball' },
  { searchTerm: 'business', label: 'Business', icon: 'money-bill-alt' },
  { searchTerm: 'world', label: 'World', icon: 'globe' },
  { searchTerm: 'opinion', label: 'Opinion', icon: 'comments' },
  { searchTerm: 'health', label: 'Health', icon: 'user-md' },
  { searchTerm: 'books', label: 'Books', icon: 'book-reader' },
  { searchTerm: 'fashion', label: 'Fashion', icon: 'shopping-bag' },
  { searchTerm: 'travel', label: 'Travel', icon: 'plane' },
  { searchTerm: 'home', label: 'Home', icon: 'home' },
  { searchTerm: 'magazine', label: 'Magazine', icon: 'book-open' },
  { searchTerm: 'movies', label: 'Movies', icon: 'video' },
  { searchTerm: 'science', label: 'Science', icon: 'flask' },
  { searchTerm: 'technology', label: 'Technology', icon: 'mobile-alt' },
  { searchTerm: 'upshot', label: 'Upshot', icon: 'arrow-alt-circle-up' },
  { searchTerm: 'realestate', label: 'Real Estate', icon: 'city' },
  { searchTerm: 'sundayreview', label: 'Sunday Review', icon: 'search' },
  { searchTerm: 'theater', label: 'Theater', icon: 'theater-masks' },
  { searchTerm: 'obituaries', label: 'Obituaries', icon: 'skull-crossbones' },
  { searchTerm: 'nyregion', label: 'NY Region', icon: 'apple-alt' },
  { searchTerm: 'automobiles', label: 'Automobiles', icon: 'car' }
];
